### ISSUE TITLE
Bindings.gyp not found

### ISSUE THREAD

**Issue by ayazhafiz** [mapbox/node-or-tools#32]
When doing `npm install node_or_tools` with a non-LTS Node version, I receive the following error (relevant lines are the first three):

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/node_or_tools/v1.0.3/Release/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node_or_tools@1.0.3 and node@7.10.1 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp: binding.gyp not found (cwd: /Users/.../node_modules/node_or_tools) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/.../node_modules/node_or_tools/lib/binding/node_or_tools.node" "--module_name=node_or_tools" "--module_path=/Users/.../node_modules/node_or_tools/lib/binding"
gyp ERR! cwd /Users/.../node_modules/node_or_tools
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/.../node_modules/node_or_tools/lib/binding/node_or_tools.node --module_name=node_or_tools --module_path=/Users/.../node_modules/node_or_tools/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/.../node_modules/node_or_tools/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/.../node_modules/node_or_tools/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/.../node_modules/node_or_tools
node-pre-gyp ERR! node -v v7.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/.../node_modules/node_or_tools/lib/binding/node_or_tools.node --module_name=node_or_tools --module_path=/Users/.../node_modules/node_or_tools/lib/binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node_or_tools@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
```

This seems to be caused by the [ignoring of bindings.gyp in the .npmignore](https://github.com/mapbox/node-or-tools/blob/master/.npmignore#L1). Is this intentional?

**Comment by daniel-j-h** [comment]
Oops, no that is not intentional. Thanks for catching! I will fix this and make a new point-release.

**Comment by daniel-j-h** [comment]
I just published version 1.0.4 which includes the build files - can you check and see if it works now?

**Comment by ayazhafiz** [comment]
Yep, it's all good. Thanks!

**Comment by daniel-j-h** [comment]
Perfect - Happy Routing! ✨
